// ───────────────────────── SHARED REACTION STATE ─────────────────────────
// This module centralizes the mutable, module-level state that used to live
// directly inside ChemLabCanvas.jsx.
//
// There are two distinct concepts living in this file, and they must never be
// confused with one another:
//
//   COMPOUND_BLUEPRINTS — "how do these raw atoms bond into ONE molecule?"
//     Keyed by a fingerprint of atom symbols (e.g. "H-H-O"). Each entry
//     describes a single molecule's internal atom-to-atom bond graph
//     (which atom index bonds to which, with what order/type). This powers
//     the atom-assembly sandbox: dragging loose H/H/O atoms together and
//     having the engine recognize + bond them into water. PubChem/Gemini/
//     Supabase populate this table. It NEVER describes a reaction between
//     two already-formed molecules.
//
//   REACTIONS — "what happens when these already-formed MOLECULES meet?"
//     The molecule-based reaction database (precipitation, neutralization,
//     combustion, decomposition, synthesis, single/double displacement...).
//     Each entry is keyed by a canonical signature of its reactant molecule
//     FORMULAS (order-independent) and looks like:
//       {
//         reactants: ["BaCl2", "Na2SO4"],
//         products: [
//           { formula: "BaSO4", coefficient: 1 },
//           { formula: "NaCl",  coefficient: 2 },
//         ],
//         name, fact, type, deltaH, ...
//       }
//     Products are ALWAYS looked up here (or generated by prediction) —
//     never synthesized by concatenating/merging reactant atoms together.
//     See reactionEngine.js / moleculeReactionResolver.js for how this is
//     consumed.

import { canonicalReactantSignature } from "./reactionUtils";

// ── Atom-assembly compound blueprints (formerly named REACTIONS) ──
export const COMPOUND_BLUEPRINTS = {};

// ── Molecule-based reaction database (the new, molecule-based REACTIONS) ──
export const REACTIONS = {};

let isReady = false;

export function isReactionStoreReady() {
  return isReady;
}

export function setReactionStoreReady(ready) {
  isReady = !!ready;
}

export function clearReactions() {
  for (const key in REACTIONS) {
    delete REACTIONS[key];
  }
}

/**
 * Registers a molecule-based reaction entry under its canonical reactant
 * signature so the resolver can look it up regardless of the order the
 * reactant molecules were listed/placed in (BaCl2 + Na2SO4 === Na2SO4 + BaCl2).
 */
export function registerReaction(entry) {
  if (!entry || !Array.isArray(entry.reactants) || entry.reactants.length === 0) return;
  const key = canonicalReactantSignature(entry.reactants);
  REACTIONS[key] = entry;
  return key;
}

/**
 * Finds a known atom-bond blueprint for a given product molecule formula
 * (e.g. "NaCl"), if one has already been resolved/cached. Used when the
 * reaction engine needs to spawn a product molecule's atoms+bonds on the
 * canvas — falls back to an async PubChem/Gemini lookup (see
 * findCompoundEntry in reactionResolutionService.js) when nothing is cached.
 */
export function findBlueprintByFormula(formula) {
  if (!formula) return null;
  for (const key in COMPOUND_BLUEPRINTS) {
    if (COMPOUND_BLUEPRINTS[key]?.formula === formula) return COMPOUND_BLUEPRINTS[key];
  }
  return null;
}

export const backgroundLookupQueue = new Set();

// prevent duplicate in-flight requests for same fingerprint
export const pendingLookups = new Set();

// Loaded from environment variables. Read-only — no runtime setters.
// Model selection is a deployment/configuration concern (edit .env, restart dev server).
export const FIREWORKS_API_KEY = import.meta.env.VITE_FIREWORKS_API_KEY || null;
export const FIREWORKS_MODEL = import.meta.env.VITE_FIREWORKS_MODEL || null;

if (!FIREWORKS_MODEL) {
  console.error("[ChemLab] VITE_FIREWORKS_MODEL is not configured. Set it in your .env file (e.g. VITE_FIREWORKS_MODEL=accounts/fireworks/models/qwen3p7-plus).");
}


// "Search Online" toggle (Upgrade #10.1): when false, PubChem's live network
// lookup is skipped entirely and resolution falls back to whatever's already
// in the in-memory COMPOUND_BLUEPRINTS table / Supabase cache. Gemini
// generation is unaffected by this toggle — it's a separate, explicitly-opt-in
// AI source.
export let SEARCH_ONLINE_ENABLED = true;

export function setSearchOnlineEnabled(enabled) {
  SEARCH_ONLINE_ENABLED = !!enabled;
}

// Global search generation counter — only the latest generation can commit.
// Exposed via functions (rather than a raw exported `let`) because ES module
// bindings for `let`/`var` are read-only from importing modules, and the
// component needs to increment this on every new inventory search.
let inventorySearchGeneration = 0;

export function getInventorySearchGeneration() {
  return inventorySearchGeneration;
}

export function bumpInventorySearchGeneration() {
  inventorySearchGeneration += 1;
  return inventorySearchGeneration;
}
